# Generated by Django 5.0.4 on 2024-05-01 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='is_staff',
            new_name='is_admin',
        ),
    ]
