# Generated by Django 5.0.4 on 2024-05-02 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_useraccount_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
