# Generated by Django 5.0.4 on 2024-05-02 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_useraccount_birth_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='birth_date',
        ),
    ]
