# Generated by Django 5.0.4 on 2024-05-02 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_useraccount_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='birth_date',
            field=models.DateField(null=True),
        ),
    ]
